version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cleaner
      MYSQL_USER: cleaner
      MYSQL_PASSWORD: password
    ports:
    - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3005:80"
    links:
      - db